name: Release image

on:
  push:
    branches: [main]

  workflow_dispatch:
    inputs:
      version:
        description: "Github Actions runner version"
        default: "latest"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push base image
        uses: ./.github/actions/push
        with:
          dockerfile-path: Dockerfile.base
          image-name: ghcr.io/${{ github.repository }}/base
          version: ${{ github.event.inputs.version }}
          build-args: |
              RUNNER_VERSION=${{ github.event.inputs.version }}

      - name: Build and push backend image
        uses: ./.github/actions/push
        with:
          dockerfile-path: Dockerfile.base
          image-name: ghcr.io/${{ github.repository }}/backend
          version: ${{ github.event.inputs.version }}
          build-args: |
            RUNNER_VERSION=${{ github.event.inputs.version }}
            GO_VERSION=1.24.3
            GORELEASER_VERSION=v2.8.2
            GOLANGCI_LINT_VERSION=v1.64.8